// Car body types
export const CAR_TYPES = [
  { id: 'sedan', label: 'Sedan', icon: '🚗' },
  { id: 'suv', label: 'SUV', icon: '🚙' },
  { id: 'coupe', label: 'Coupe', icon: '🏎️' },
  { id: 'hatchback', label: 'Hatchback', icon: '🚕' },
  { id: 'truck', label: 'Truck', icon: '🛻' },
  { id: 'van', label: 'Van', icon: '🚐' },
  { id: 'convertible', label: 'Convertible', icon: '🏖️' },
  { id: 'wagon', label: 'Wagon', icon: '🚐' },
] as const;

// Comprehensive list of car brands from all regions (alphabetically sorted)
// Includes expanded Chinese brands due to growing popularity in Kuwait/Middle East
export const CAR_BRANDS = [
  'Acura',
  'Alfa Romeo',
  'Aston Martin',
  'Audi',
  'BAIC',
  'Bentley',
  'BMW',
  'Bugatti',
  'Buick',
  'BYD',
  'Cadillac',
  'Changan',
  'Chery',
  'Chevrolet',
  'Chrysler',
  'Citroën',
  'Dacia',
  'Daewoo',
  'Daihatsu',
  'Dodge',
  'Dongfeng',
  'FAW',
  'Ferrari',
  'Fiat',
  'Ford',
  'Foton',
  'GAC',
  'Geely',
  'Genesis',
  'GMC',
  'Great Wall',
  'Haval',
  'Honda',
  'Hongqi',
  'Hummer',
  'Hyundai',
  'Infiniti',
  'Isuzu',
  'JAC',
  'Jaguar',
  'Jeep',
  'Jetour',
  'Kia',
  'Koenigsegg',
  'Lada',
  'Lamborghini',
  'Lancia',
  'Land Rover',
  'Lexus',
  'Li Auto',
  'Lincoln',
  'Lotus',
  'Lynk & Co',
  'Maserati',
  'Maxus',
  'Maybach',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'MG',
  'Mini',
  'Mitsubishi',
  'NIO',
  'Nissan',
  'Omoda',
  'Opel',
  'ORA',
  'Pagani',
  'Peugeot',
  'Polestar',
  'Pontiac',
  'Porsche',
  'Proton',
  'Ram',
  'Renault',
  'Rolls-Royce',
  'Saab',
  'Saturn',
  'Scion',
  'SEAT',
  'Skoda',
  'Smart',
  'SsangYong',
  'Subaru',
  'Suzuki',
  'Tank',
  'Tata',
  'Tesla',
  'Toyota',
  'Vauxhall',
  'Volkswagen',
  'Volvo',
  'Wuling',
  'XPeng',
  'Zeekr',
  'Other',
] as const;

export type CarType = typeof CAR_TYPES[number]['id'];
export type CarBrand = typeof CAR_BRANDS[number];
